#pseudocode
#SQUARE-MATRIX-MULTIPLY-RECURSIVE(A,B)
#	n = A.rows
#	let C be a new n x n matrix
#	if n == 1
#		c11 = a11 * b11
#	else partition A,B, and C as in 4.9 (clrs 76)
#		C11 = SQUARE-MATRIX-MULTIPLY-RECURSIVE(A11,B11) +
#			SQUARE-MATRIX-MULTIPLY-RECURSIVE(A12,B21)
#		C12 = SQUARE-MATRIX-MULTIPLY-RECURSIVE(A11,B12) +
#			SQUARE-MATRIX-MULTIPLY-RECURSIVE(A12,B22)
#		C21 = SQUARE-MATRIX-MULTIPLY-RECURSIVE(A21,B11) + 
#			SQUARE-MATRIX-MULTIPLY-RECURSIVE(A22,B21)
#		C22 = SQUARE-MATRIX-MULTIPL-RECURSIVE(A21,B12) +
#			SQUARE-MATRIX-MULTIPLY-RECURSIVE(A22,B22)
#	return C 
